config/routes.rb
Rails.application.routes.draw do
  get 'about' => 'static#about'

  get 'random' => 'static#random'

  root 'ideas#index'
  resources :ideas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :description, :author, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @ideas = Idea.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
  end

  def create
    # @idea = Idea.create(description: params[:idea][:description], author: params[:idea][:description])
    # @idea = Idea.create(params[:idea])
    @idea = Idea.create(idea_params)
    if @idea.valid?
      flash[:success] = "Hoorah! You created a new Idea..."
    else
      flash[:alert] = "Failed!!! Something is wrong with your input data"
    end
    redirect_to root_path
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def update
    @idea = Idea.find(params[:id])
    if @idea.update(idea_params)
      flash[:success] = "Successfully updated the Idea..."
      redirect_to root_path
    else
      flash[:alert] = "Failed to update the Idea..."
      redirect_to edit_idea_path(params[:id])
    end
  end 

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    flash[:notice] = "Successfully deleted the Idea..."
    redirect_to root_path
  end

  private

  def idea_params
    params.require(:idea).permit(:description, :author)
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def about
  end

  def random
    @idea = Idea.order("RANDOM()").first  
    # @idea = Idea.all.sample
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/ideas/edit.html.erb
<h1>Revise Idea</h1>

<%= simple_form_for @idea, method: :patch do |f| %>
  <%= f.input :description %>
  <%= f.input :author %>
  <%= f.submit 'Submit', class: "btn btn-primary" %>
<% end %>

app/views/ideas/index.html.erb
<%= simple_form_for Idea.new do |f| %>

<button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#myModal">
  Add Idea
</button>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h4 class="modal-title" id="myModalLabel">Your Idea</h4>
      </div>
      <div class="modal-body">
          <%= f.input :description %>
          <%= f.input :author %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>
<% end %>

<% @ideas.each do |idea| %>
  <div class="panel panel-default">
    <div class="panel-body">
      <blockquote>
        <p><%= idea.description %></p>
        <small><%= idea.author %></small>  
      </blockquote>
      <br>
      <div class="btn-group" role="group">
        <%= link_to "Delete", idea_path(idea), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} %>
        <%= link_to 'Revise', edit_idea_path(idea), class: 'btn btn-sm btn-success' %>
      </div>
    </div>
  </div>
<% end %>

<div class="text-center">
  <%= will_paginate @ideas %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ideator</title>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Dosis|Open+Sans:300,400,600,700" rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <div id="wrap">
    <%= render 'shared/nav' %>
    <div class = "container">
      <div class = "row">
        <div class = "col-xs-12 col-md-8 col-md-offset-2">
          <%= render 'shared/flash' %>
          <%= yield %>
        </div>
      </div>
    </div>  
  </div> <!-- #Wrap -->
  
  <%= render 'shared/footer' %>

</body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "notice" %>
    <p class="alert alert-info alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= notice %></p>
  <% elsif message_type == "alert" %>
    <p class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= alert %></p>
  <% else %>
    <div class="alert alert-<%= message_type %> alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer text-center">
  <p><span>© Srijal Joshi</span> <%= Date.today.year %> All Rights Reserved</p>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Ideator</a>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "All Ideas", ideas_path %></li>
      <li><%= link_to "Inspire Me", random_path %></li>
      <li><%= link_to "About", about_path %></li>
    </ul>

  </div><!-- /.container-fluid -->
</nav>